<?xml version="1.0" encoding="UTF-8"?>
<!--
  Purpose:
    XSLT stylesheet to convert product configuration (version 6) to
    new portal configuration (version 7)

  Input:
    - Stitchfile of product configuration XML file (version 6)

  Output:
    - portal configuration XML file (version 7)

  Parameters:
    - use.xincludes: Whether to use xi:include for chunking output (default: false)
    - outputdir: The directory to write output files to (default: 'output/')
    - outputfile: The main output filename (default: 'portal.xml')
    - schemafile: The RNG schema file that is referenced in a `<?xml-model?>
      processing instruction at the header (default empty)
    - schemaversion: The schemaversion attribute to set in the output XML (default: '7.0')
    - cat.prefix: Use only for category ID, a prefix to be added before the ID to avoid duplication (default "cat.")

  Author:
    Tom Schraitle

  Copyright (C) 2026 SUSE Linux GmbH
-->
<!DOCTYPE xsl:stylesheet [
  <!ENTITY uppercase "'ABCDEFGHIJKLMNOPQRSTUVWXYZ'">
  <!ENTITY lowercase "'abcdefghijklmnopqrstuvwxyz'">
]>
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:xi="http://www.w3.org/2001/XInclude"
  xmlns:exsl="http://exslt.org/common"
  exclude-result-prefixes="exsl"
  extension-element-prefixes="exsl">

  <xsl:output encoding="UTF-8" indent="yes" method="xml"/>
  <xsl:strip-space elements="*"/>
  <xsl:preserve-space elements="p div pre h1 h2 h3 h4 h5 h6 li dt dd span em strong code q s u sub sup cite a br hr title subtitle desc"/>

<!-- ======== Parameters -->
  <xsl:param name="use.xincludes" select="false()" />

  <!-- Set the output directory -->
  <xsl:param name="outputdir" select="'output/'" />

  <!-- Set the main output filename -->
  <xsl:param name="outputfile" select="'portal.xml'" />

  <!-- Set the RNC schema file -->
  <xsl:param name="schemafile"></xsl:param>

  <!-- Set the schemaversion attribute in the output XML -->
  <xsl:param name="schemaversion">7.0</xsl:param>

  <!-- ID separator for autogenerated IDs -->
  <xsl:param name="id.sep">.</xsl:param>

  <!--  Use only for category ID, a prefix to be added before the ID to avoid duplication -->
  <xsl:param name="cat.prefix">cat.</xsl:param>

  <!-- Should sitemap be generated for translations? -->
  <xsl:param name="sitemap.for.translations">false</xsl:param>

<!-- ======== Keys -->
  <!-- Define a key to group <language> elements by their @lang attribute -->
  <xsl:key name="langKey" match="category/language[not(ancestor-or-self::product)]" use="@lang" />
  <!-- Define a key to group product category <language> elements by product ID and @lang -->
  <xsl:key name="productCategoryLangKey" match="product/category/language" use="concat(ancestor::product[1]/@productid, '|', @lang)" />


<!-- ======== Variables -->
  <xsl:variable name="_transformation-map">
    <!--
      Attributes:
      * id (ID): the product ID
      * series (str): the series that this product belongs
      * family (str): the product family that this product belongs
      * rank (int): The product rank that influences the tiles on the portal homepage
      * idabbrev (str): The product ID abbreviation used in <deliverable id="...">. The IDs for
        products are not changed.
    -->
    <config>
      <product id="appliance" series="s.pas" family="f.linux" rank="04150" idabbrev="app"/>
      <product id="cloudnative" series="s.pas" family="f.cn" rank="00030" idabbrev="cn" />
      <product id="container" series="s.pas" family="f.linux" rank="04130" idabbrev="cont" />
      <product id="compliance" series="s.pas" family="f.linux" rank="04130" idabbrev="comp" />
      <product id="liberty" series="s.pas" family="f.linux" rank="00060" idabbrev="lib" />
      <product id="releasenotes" series="s.rn" family="f.linux" idabbrev="rn" rank="0"/>
      <product id="sbp" series="s.sbp" family="f.linux" rank="0" />
      <product id="ses" series="s.pas" family="f.linux" rank="04160" />
      <product id="sled" series="s.pas" family="f.linux" rank="04100" />
      <product id="sle-ha" series="s.pas" family="f.linux" rank="04070" />
      <product id="sle-hpc" series="s.pas" family="f.linux" rank="04110" />
      <product id="sle-micro" series="s.pas" family="f.linux" rank="00020" />
      <product id="sle-public-cloud" series="s.pas" family="f.linux" rank="04060" idabbrev="spc" />
      <product id="sle-rt" series="s.pas" family="f.linux" rank="04080" />
      <product id="sles-sap" series="s.pas" family="f.linux" rank="00050" />
      <product id="sles" series="s.pas" family="f.linux" rank="00080" />
      <product id="sle-vmdp" series="s.pas" family="f.linux" rank="04120" />
      <product id="smart" series="s.pas" family="f.linux" rank="0"/>
      <product id="smt" series="s.pas" family="f.linux" rank="04330" />
      <product id="soc" series="s.pas" family="f.linux" rank="04300" />
      <product id="style" series="s.pas" family="f.linux" rank="0"/>
      <product id="subscription" series="s.pas" family="f.linux" rank="04140" idabbrev="sub" />
      <product id="suma" series="s.pas" family="f.linux" rank="0"/>
      <product id="suma-retail" series="s.pas" family="f.linux" rank="0"/>
      <product id="suse-ai" series="s.pas" family="f.suse-ai" rank="00010" />
      <product id="suse-caasp" series="s.pas" family="f.linux" rank="04310" />
      <product id="suse-cap" series="s.pas" family="f.linux" rank="04320"/>
      <product id="suse-distribution-migration-system" series="s.pas" family="f.linux" idabbrev="suma-dms" rank="0"/>
      <product id="suse-edge" series="s.pas" family="f.suse-edge" rank="00040" />
      <product id="trd" series="s.trd" family="f.linux" rank="0"/>
    </config>
  </xsl:variable>
  <xsl:variable name="config" select="exsl:node-set($_transformation-map)/*" />
  <xsl:variable name="blocked.category.ids" select="'|about|deployment|update-upgrade|administration|container-virtualization|product-usage|security-compliance|tuning-performance|solution-doc|additional-doc|best-pratices|best-practices|'"/>


<!-- ======== Helper functions -->
<!--
    Template: write.file
    Writes content to a file.
    Parameters:
      filename - The filename to write to
      content - The content to write
      method - Output method (default: xml)
      encoding - Output encoding (default: UTF-8)
      indent - Whether to indent output (default: yes)
  -->
  <xsl:template name="write.file">
    <xsl:param name="filename"/>
    <xsl:param name="content"/>
    <xsl:param name="debug" select="1" />
    <xsl:param name="method" select="'xml'"/>
    <xsl:param name="encoding" select="'UTF-8'"/>
    <xsl:param name="indent" select="'yes'"/>

    <exsl:document href="{$filename}"
                   method="{$method}"
                   encoding="{$encoding}"
                   indent="{$indent}">
      <xsl:copy-of select="$content"/>
    </exsl:document>
    <xsl:if test="boolean($debug)">
      <xsl:message>Written file: <xsl:value-of select="concat('&quot;', $filename, '&quot;')" /></xsl:message>
    </xsl:if>
  </xsl:template>

  <!--
    Template: write.chunk
    Handles the logic for writing a chunk to a file or inlining it.
    Parameters:
      filename - The relative path to the output file (from outputdir)
      hreftype - The href to use for xi:include
                 Possible values: 'filename' (default), 'relative', 'none'
      content - The content to Write
  -->
  <xsl:template name="write.chunk">
    <xsl:param name="filename"/>
    <xsl:param name="hreftype" select="'filename'"/>
    <xsl:param name="manual_href" select="''"/>
    <xsl:param name="content"/>

    <xsl:choose>
      <xsl:when test="(string($use.xincludes) = 'true' or string($use.xincludes) = '1') and $filename != ''">
        <xsl:variable name="href">
           <xsl:choose>
             <xsl:when test="string($manual_href) != ''">
               <xsl:value-of select="$manual_href"/>
             </xsl:when>
             <xsl:when test="$hreftype = 'relative'">
               <xsl:call-template name="substring-after-last">
                 <xsl:with-param name="string" select="$filename"/>
                 <xsl:with-param name="char" select="'/'"/>
               </xsl:call-template>
             </xsl:when>
             <xsl:otherwise>
               <xsl:value-of select="$filename"/>
             </xsl:otherwise>
           </xsl:choose>
        </xsl:variable>

        <!-- <xi:include href="{$href}"/>-->
        <xsl:element name="xi:include" namespace="http://www.w3.org/2001/XInclude">
          <xsl:attribute name="href">
            <xsl:value-of select="$href"/>
          </xsl:attribute>
        </xsl:element>

        <xsl:call-template name="write.file">
          <xsl:with-param name="filename" select="concat($outputdir, $filename)"/>
          <xsl:with-param name="content" select="$content"/>
        </xsl:call-template>
      </xsl:when>
      <xsl:otherwise>
        <xsl:copy-of select="$content"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <xsl:template name="substring-after-last">
    <xsl:param name="string" />
    <xsl:param name="char" />
    <xsl:choose>
      <xsl:when test="contains($string, $char)">
        <xsl:call-template name="substring-after-last">
          <xsl:with-param name="string" select="substring-after($string, $char)" />
          <xsl:with-param name="char" select="$char" />
        </xsl:call-template>
      </xsl:when>
      <xsl:otherwise>
        <xsl:value-of select="$string" />
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <xsl:template name="add-pi-for-relaxng">
    <xsl:variable name="ext" select="substring($schemafile, string-length($schemafile) - 3)" />
    <xsl:if test="$schemafile != ''">
      <xsl:variable name="type">
        <xsl:choose>
          <xsl:when test="$ext = '.rnc'">application/relax-ng-compact-syntax</xsl:when>
          <xsl:when test="$ext = '.rng'">application/xml</xsl:when>
          <xsl:otherwise>
            <xsl:message terminate="yes">
              <xsl:text>Error: Unknown schema file extension for </xsl:text>
              <xsl:value-of select="$schemafile"/>
              <xsl:text>. Only .rnc and .rng are supported.</xsl:text>
            </xsl:message>
          </xsl:otherwise>
        </xsl:choose>
      </xsl:variable>
      <xsl:processing-instruction name="xml-model">
        <xsl:value-of select="concat('href=&quot;', $schemafile, '&quot;')"/>
        <xsl:value-of select="concat(' type=&quot;', $type, '&quot;')"/>
      </xsl:processing-instruction>
      <xsl:text>&#10;</xsl:text>
    </xsl:if>
  </xsl:template>

  <xsl:template name="generate.id">
    <xsl:param name="product.idabbrev"/>
    <xsl:param name="docset"/>
    <xsl:param name="dc"/>
    <xsl:variable name="docset.norm" select="normalize-space($docset)"/>
    <xsl:variable name="dc.norm" select="normalize-space($dc)"/>

    <xsl:value-of select="$product.idabbrev"/>

    <xsl:if test="$docset.norm">
      <xsl:value-of select="$id.sep"/>
      <xsl:value-of select="$docset.norm"/>
    </xsl:if>

    <xsl:if test="$dc.norm">
      <xsl:value-of select="$id.sep"/>
      <xsl:value-of select="translate(
                              translate($dc.norm, &uppercase;, &lowercase;),
                              ' /', '--'
                            )"/>
    </xsl:if>
  </xsl:template>

  <xsl:template name="unique-category-id">
    <xsl:param name="node" select="." />
    <xsl:param name="productid" select="$node/ancestor::product/@productid"/>
    <xsl:param name="categoryid" select="$node/@categoryid"/>

    <xsl:value-of select="concat($cat.prefix, $productid, $id.sep, $categoryid)"/>
  </xsl:template>

  <xsl:template name="write-category-attribute">
    <xsl:param name="categoryid" select="."/>
    <xsl:param name="productid" select="ancestor::product/@productid"/>
    <xsl:param name="has-product-categories" select="ancestor::product/category"/>
    <xsl:variable name="categoryid.raw" select="normalize-space(string($categoryid))"/>
    <xsl:variable name="categoryid.norm">
      <xsl:choose>
        <xsl:when test="starts-with($categoryid.raw, $cat.prefix)">
          <xsl:value-of select="substring-after($categoryid.raw, $cat.prefix)"/>
        </xsl:when>
        <xsl:otherwise>
          <xsl:value-of select="$categoryid.raw"/>
        </xsl:otherwise>
      </xsl:choose>
    </xsl:variable>

    <xsl:attribute name="category">
      <xsl:choose>
        <!-- Same blocked list as in product/category[1] template: these are always global -->
        <xsl:when test="not(contains($blocked.category.ids, concat('|', $categoryid.norm, '|'))) and $has-product-categories[@categoryid = $categoryid.norm]">
          <xsl:call-template name="unique-category-id">
            <xsl:with-param name="productid" select="$productid"/>
            <xsl:with-param name="categoryid" select="$categoryid.norm"/>
          </xsl:call-template>
        </xsl:when>
        <!-- Alias legacy cross-product references to existing category owners -->
        <xsl:when test="$categoryid.norm = 'smart-docs' and $productid = 'sles-sap' and /docservconfig/product[@productid = 'sles']/category[@categoryid = 'smart-docs']">
          <xsl:call-template name="unique-category-id">
            <xsl:with-param name="productid" select="'sles'"/>
            <xsl:with-param name="categoryid" select="$categoryid.norm"/>
          </xsl:call-template>
        </xsl:when>
        <xsl:when test="$categoryid.norm = 'core-doc' and $productid = 'suma-retail' and /docservconfig/product[@productid = 'suma']/category[@categoryid = 'core-doc']">
          <xsl:call-template name="unique-category-id">
            <xsl:with-param name="productid" select="'suma'"/>
            <xsl:with-param name="categoryid" select="$categoryid.norm"/>
          </xsl:call-template>
        </xsl:when>
        <xsl:otherwise>
          <xsl:value-of select="concat($cat.prefix, $categoryid.norm)"/>
        </xsl:otherwise>
      </xsl:choose>
    </xsl:attribute>
  </xsl:template>


<!-- ======== General Templates -->
  <xsl:template match="node() | @*" name="copy">
      <xsl:copy>
        <xsl:apply-templates select="node() | @*" />
      </xsl:copy>
  </xsl:template>


  <!-- ========  Ignore Templates -->
  <xsl:template match="/docservconfig/hashes"/>
  <xsl:template match="p[not(*) and not(text()[normalize-space()])]"/>

  <xsl:template match="processing-instruction('xml-model')" />


  <!-- ========  Templates -->
  <xsl:template match="/docservconfig">
    <xsl:call-template name="write.file">
      <xsl:with-param name="filename" select="concat($outputdir, $outputfile)" />
      <xsl:with-param name="content">
        <xsl:call-template name="add-pi-for-relaxng" />
        <portal schemaversion="{$schemaversion}" xmlns:xi="http://www.w3.org/2001/XInclude">
          <xsl:apply-templates select="categories" />
          <productfamilies>
            <item id="f.linux">Linux</item>
            <item id="f.cn">Cloud Native</item>
            <item id="f.suse-edge">SUSE Edge</item>
            <item id="f.suse-ai">SUSE AI</item>
          </productfamilies>
          <series>
            <item id="s.pas">Products &amp; Solutions</item>
            <item id="s.sbp" >SUSE Best Practices</item>
            <item id="s.trd">Technical References</item>
            <item id="s.rn">Release Notes</item>
          </series>
          <!-- <xi:include href="categories.xml" />
          <xsl:element name="include" namespace="http://www.w3.org/2001/XInclude">
            <xsl:attribute name="href">categories.xml</xsl:attribute>
          </xsl:element>
          -->
          <xsl:apply-templates select="*[not(self::categories)]" />
        </portal>
      </xsl:with-param>
    </xsl:call-template>
  </xsl:template>

  <xsl:template match="/docservconfig/categories">
    <xsl:variable name="content">
      <xsl:apply-templates select="." mode="render"/>
    </xsl:variable>

    <xsl:call-template name="write.chunk">
      <xsl:with-param name="filename" select="'categories.xml'"/>
      <xsl:with-param name="content" select="$content"/>
    </xsl:call-template>
  </xsl:template>

  <xsl:template match="/docservconfig/categories" mode="render">
    <categories xmlns:xi="http://www.w3.org/2001/XInclude">
      <xsl:copy-of select="@*"/>
      <!-- Select only the first occurring <language> element for each unique @lang -->
      <xsl:for-each select="category/language[generate-id() = generate-id(key('langKey', @lang)[1])]">
        <xsl:variable name="currentLang" select="@lang" />

        <xsl:variable name="content">
          <!-- Create the new <category> element grouped by language -->
          <category lang="{$currentLang}">

            <!-- Retrieve all <language> elements that match the current @lang -->
            <xsl:for-each select="key('langKey', $currentLang)">
               <!-- Create an <language> for each, pulling categoryid from its parent -->
                <xsl:choose>
                  <xsl:when test=" starts-with($currentLang, 'en')">
                    <language id="{concat($cat.prefix, ../@categoryid)}"
                              title="{@title}">
                      <xsl:apply-templates select="node()"/>
                    </language>
                  </xsl:when>
                  <xsl:otherwise>
                    <language linkend="{concat($cat.prefix, ../@categoryid)}"
                              title="{@title}">
                      <xsl:apply-templates select="node()"/>
                    </language>
                  </xsl:otherwise>
                </xsl:choose>
            </xsl:for-each>
          </category>
        </xsl:variable>

        <xsl:call-template name="write.chunk">
           <xsl:with-param name="filename" select="concat('categories/', $currentLang, '.xml')"/>
           <xsl:with-param name="content" select="$content"/>
        </xsl:call-template>
      </xsl:for-each>
    </categories>
  </xsl:template>

  <!-- Product  -->
  <!-- don't copy these attributes -->
  <xsl:template match="product/processing-instruction()" />
  <xsl:template match="product/@schemaversion" />
  <xsl:template match="product/@site-section" />

  <xsl:template match="product/@productid">
    <xsl:variable name="id" select="." />
    <xsl:attribute name="id">
      <xsl:value-of select="$id" />
    </xsl:attribute>
  </xsl:template>

  <xsl:template match="product">
    <xsl:variable name="id" select="@productid" />
    <xsl:variable name="cnfg" select="$config/product[@id=$id]" />

    <!-- Capture the product content -->
    <xsl:variable name="content">
      <xsl:apply-templates select="." mode="render"/>
    </xsl:variable>

    <xsl:call-template name="write.chunk">
      <xsl:with-param name="filename" select="concat($id, '/', $id, '.xml')"/>
       <xsl:with-param name="content" select="$content"/>
    </xsl:call-template>
  </xsl:template>

  <xsl:template match="product" mode="render">
    <xsl:variable name="id" select="@productid" />
    <xsl:variable name="cnfg" select="$config/product[@id=$id]" />
    <product xmlns:xi="http://www.w3.org/2001/XInclude">
        <xsl:apply-templates select="@*" />
        <!-- Add new attributes based on the transformation map -->
        <xsl:attribute name="family">
          <xsl:value-of select="$cnfg/@family" />
        </xsl:attribute>
        <xsl:attribute name="series">
          <xsl:value-of select="$cnfg/@series" />
        </xsl:attribute>
        <xsl:attribute name="rank">
          <xsl:value-of select="$cnfg/@rank" />
        </xsl:attribute>

<!--        <xsl:message>product (<xsl:value-of select="$id"/>):
   product node=<xsl:value-of select="count($cnfg)"/>
   family=<xsl:value-of select="$cnfg/@family"/>
   series=<xsl:value-of select="$cnfg/@series"/>
   rank=<xsl:value-of select="$cnfg/@rank"/>
        </xsl:message>-->

        <xsl:apply-templates select="name"/>
        <xsl:apply-templates select="sortname"/>
        <xsl:apply-templates select="acronym"/>
        <xsl:apply-templates select="maintainers"/>
        <xsl:apply-templates select="category"/>

        <!-- Handle desc elements -->
        <xsl:if test="desc">
          <xsl:variable name="content">
             <descriptions xmlns:xi="http://www.w3.org/2001/XInclude">
                <xsl:for-each select="desc">
                   <xsl:variable name="lang" select="@lang"/>
                   <xsl:variable name="inner_content">
                      <xsl:apply-templates select="." />
                   </xsl:variable>

                   <xsl:call-template name="write.chunk">
                      <xsl:with-param name="filename" select="concat($id, '/desc/', $lang, '.xml')"/>
                      <xsl:with-param name="hreftype" select="'relative'"/>
                      <xsl:with-param name="content" select="$inner_content"/>
                   </xsl:call-template>
                </xsl:for-each>
             </descriptions>
          </xsl:variable>

          <xsl:call-template name="write.chunk">
             <xsl:with-param name="filename" select="concat($id, '/desc/desc.xml')"/>
             <xsl:with-param name="manual_href" select="'desc/desc.xml'"/>
             <xsl:with-param name="content" select="$content"/>
          </xsl:call-template>
        </xsl:if>

        <xsl:apply-templates select="node()[not(self::desc)
                                            and not(self::name)
                                            and not(self::sortname)
                                            and not(self::acronym)
                                            and not(self::maintainers)
                                            and not(self::category)]" />
    </product>
  </xsl:template>

  <!-- Product categories are emitted under product, excluding blocked category IDs. -->
  <xsl:template match="product/category[1]">
    <xsl:variable name="selected"
                  select="../category[not(contains($blocked.category.ids, concat('|', string(@categoryid), '|')))]"/>
    <xsl:variable name="productLanguages"
                  select="$selected/language[
                    generate-id() = generate-id(
                      key('productCategoryLangKey', concat(ancestor::product[1]/@productid, '|', @lang))
                        [ancestor::category[1][not(contains($blocked.category.ids, concat('|', string(@categoryid), '|')))]]
                        [1]
                    )
                  ]"/>

    <xsl:if test="$productLanguages">
      <categories>
        <xsl:for-each select="$productLanguages">
          <xsl:variable name="currentLang" select="@lang"/>

          <category lang="{$currentLang}">
            <xsl:for-each select="$selected">
              <xsl:variable name="currentCategory" select="."/>
              <xsl:variable name="sourceLanguage"
                            select="$currentCategory/language[@lang = $currentLang][1]"/>

              <xsl:if test="$sourceLanguage">
                <language>
                  <xsl:choose>
                    <xsl:when test="starts-with($currentLang, 'en')">
                      <xsl:attribute name="id">
                        <xsl:call-template name="unique-category-id">
                          <xsl:with-param name="node" select="$currentCategory"/>
                        </xsl:call-template>
                      </xsl:attribute>
                    </xsl:when>
                    <xsl:otherwise>
                      <xsl:attribute name="linkend">
                        <xsl:call-template name="unique-category-id">
                          <xsl:with-param name="node" select="$currentCategory"/>
                        </xsl:call-template>
                      </xsl:attribute>
                    </xsl:otherwise>
                  </xsl:choose>

                  <xsl:attribute name="title">
                    <xsl:choose>
                      <xsl:when test="$sourceLanguage/@title">
                        <xsl:value-of select="$sourceLanguage/@title"/>
                      </xsl:when>
                      <xsl:when test="$currentCategory/language[@lang='en-us'][1]/@title">
                        <xsl:value-of select="$currentCategory/language[@lang='en-us'][1]/@title"/>
                      </xsl:when>
                      <xsl:when test="$currentCategory/language[1]/@title">
                        <xsl:value-of select="$currentCategory/language[1]/@title"/>
                      </xsl:when>
                      <xsl:otherwise>
                        <xsl:value-of select="string($currentCategory/@categoryid)"/>
                      </xsl:otherwise>
                    </xsl:choose>
                  </xsl:attribute>

                  <xsl:apply-templates select="$sourceLanguage/node()"/>
                </language>
              </xsl:if>
            </xsl:for-each>
          </category>
        </xsl:for-each>
      </categories>
    </xsl:if>
  </xsl:template>

  <xsl:template match="product/category[position() &gt; 1]" />

  <xsl:template match="product/desc/@default" />

  <!-- Docset -->
  <xsl:template match="docset/@schemaversion" />
  <xsl:template match="docset/processing-instruction()" />

  <xsl:template match="docset">
     <xsl:variable name="id" select="ancestor::product/@productid"/>
     <xsl:variable name="ver" select="@setid"/>
     <xsl:variable name="subpath" select="concat($id, '/', $ver, '.xml')"/>
<!--    <xsl:variable name="" select=""/>-->

     <xsl:variable name="content">
        <docset xmlns:xi="http://www.w3.org/2001/XInclude">

          <xsl:choose>
            <xsl:when test="builddocs">
              <xsl:apply-templates select="@*|node()[not(self::external)]" />
            </xsl:when>
            <xsl:otherwise>
              <xsl:apply-templates select="@*|node()[
                                             not(self::external or
                                                 self::internal)
                                           ]" />
              <xsl:if test="external/link[not(starts-with(language/url/@href, 'https://'))
                                          and not(starts-with(language/url/@href, 'external-tree'))
                                          and not(language/url/@format = 'pdf')
                                          ]">
                 <xsl:call-template name="docset-without-builddocs" />
              </xsl:if>

              <xsl:apply-templates select="internal" />

              <xsl:if test="external/link[starts-with(language/url/@href, 'https://')
                            or language/url/@format = 'pdf']">
                 <external>
                    <xsl:apply-templates select="external/link[starts-with(language/url/@href, 'https://')
                                                 or language/url/@format = 'pdf']" mode="external-link"/>
                 </external>
              </xsl:if>
            </xsl:otherwise>
          </xsl:choose>
        </docset>
     </xsl:variable>

     <xsl:call-template name="write.chunk">
        <xsl:with-param name="filename" select="$subpath"/>
        <xsl:with-param name="hreftype" select="'relative'"/>
        <xsl:with-param name="content" select="$content"/>
     </xsl:call-template>
  </xsl:template>

  <xsl:template match="docset/@setid">
    <xsl:attribute name="id">
      <xsl:value-of select="concat(ancestor::product/@productid, $id.sep, .)" />
    </xsl:attribute>
    <xsl:attribute name="path">
      <xsl:value-of select="."/>
    </xsl:attribute>
  </xsl:template>

  <xsl:template match="docset/overridedesc">
    <descriptions>
      <xsl:copy-of select="@*"/>
      <xsl:apply-templates/>
    </descriptions>
  </xsl:template>

  <xsl:template match="docset/builddocs">
    <resources>
      <xsl:apply-templates />
    </resources>
  </xsl:template>

  <xsl:template name="docset-without-builddocs">
    <resources>
      <git remote="https://TODO" />
       <xsl:apply-templates select="external[link[not(starts-with(language/url/@href, 'https://')) and not(language/url/@format = 'pdf')]]"
         mode="builddocs" />
    </resources>
  </xsl:template>


  <xsl:template match="docset/external" mode="builddocs">
    <locale lang="en-us">
      <branch>main</branch>
      <xsl:apply-templates select="link[not(starts-with(language/url/@href, 'https://')) and not(language/url/@format = 'pdf')]" mode="builddocs" />
    </locale>
    <xsl:if test="link[not(starts-with(language/url/@href, 'https://')) and not(language/url/@format = 'pdf') and @lang != 'en-us']">
      <xsl:message>TODO: Found non-English links in docset/external</xsl:message>
    </xsl:if>
  </xsl:template>

  <xsl:template match="link" mode="external-link">
    <link>
      <xsl:apply-templates select="@gated|@titleformat|@category"/>

      <xsl:for-each select="language/url">
         <url>
           <xsl:copy-of select="@href|@format|../@lang"/>
         </url>
      </xsl:for-each>

      <descriptions>
        <xsl:for-each select="language">
          <desc>
             <xsl:attribute name="lang">
               <xsl:choose>
                 <xsl:when test="@lang"><xsl:value-of select="@lang"/></xsl:when>
                 <xsl:otherwise>en-us</xsl:otherwise>
               </xsl:choose>
             </xsl:attribute>
             <xsl:if test="@title">
               <title><xsl:value-of select="@title"/></title>
             </xsl:if>
             <p>TODO</p>
          </desc>
        </xsl:for-each>
      </descriptions>
    </link>
  </xsl:template>

  <xsl:template match="link/@*">
    <xsl:copy-of select="." />
  </xsl:template>

  <xsl:template match="link/@category">
    <xsl:apply-templates select="." mode="builddocs" />
  </xsl:template>

  <xsl:template match="link" mode="builddocs">
    <xsl:variable name="url" select="language[@lang='en-us']/url"/>
    <xsl:variable name="href" select="$url/@href"/>
    <xsl:variable name="format" select="$url/@format"/>

    <!-- Extract product ID from URL like /product/docset/... -->
    <xsl:variable name="pid">
      <xsl:choose>
        <xsl:when test="starts-with($href, '/')">
           <xsl:value-of select="substring-before(substring-after($href, '/'), '/')"/>
        </xsl:when>
        <xsl:when test="contains($href, 'external-tree')">
           <!-- href="external-tree/en-us/liberty/..." -->
           <xsl:value-of select="substring-before(substring-after(substring-after($href, 'external-tree/'), '/'), '/')"/>
        </xsl:when>
        <xsl:otherwise>
           <xsl:value-of select="ancestor::product/@productid"/>
        </xsl:otherwise>
      </xsl:choose>
    </xsl:variable>

    <xsl:variable name="abbrev" select="$config/product[@id=$pid]/@idabbrev"/>

    <xsl:variable name="product.idabbrev">
      <xsl:choose>
        <xsl:when test="string($abbrev) != ''">
          <xsl:value-of select="$abbrev"/>
        </xsl:when>
        <xsl:otherwise>
          <xsl:value-of select="$pid"/>
        </xsl:otherwise>
      </xsl:choose>
    </xsl:variable>

    <xsl:variable name="docset_from_url">
      <xsl:choose>
        <xsl:when test="starts-with($href, '/')">
           <xsl:variable name="after_pid" select="substring-after(substring-after($href, '/'), '/')"/>
           <xsl:choose>
             <xsl:when test="contains($after_pid, '/')">
               <xsl:value-of select="substring-before($after_pid, '/')"/>
             </xsl:when>
             <xsl:otherwise>
               <xsl:value-of select="$after_pid"/>
             </xsl:otherwise>
           </xsl:choose>
        </xsl:when>
        <xsl:when test="contains($href, 'external-tree')">
           <xsl:variable name="after_pid" select="substring-after(substring-after(substring-after($href, 'external-tree/'), '/'), '/')"/>
           <xsl:choose>
             <xsl:when test="contains($after_pid, '/')">
               <xsl:value-of select="substring-before($after_pid, '/')"/>
             </xsl:when>
             <xsl:otherwise>
               <xsl:value-of select="$after_pid"/>
             </xsl:otherwise>
           </xsl:choose>
        </xsl:when>
        <xsl:otherwise>
           <xsl:value-of select="ancestor::docset/@setid"/>
        </xsl:otherwise>
      </xsl:choose>
    </xsl:variable>

    <xsl:variable name="docset_for_id">
      <xsl:choose>
        <!-- For /releasenotes/<product>/<major>/ links, include the real source docset setid for uniqueness. -->
        <xsl:when test="starts-with($href, '/releasenotes/')
                        and starts-with($href, concat('/releasenotes/', ancestor::product/@productid, '/'))
                        and string(normalize-space(ancestor::docset/@setid))">
          <xsl:value-of select="concat($docset_from_url, $id.sep, ancestor::docset/@setid)"/>
        </xsl:when>
        <!-- Same issue for shared Security docs reused in multiple source docsets (for example SUSE Edge). -->
        <xsl:when test="starts-with($href, '/cloudnative/security/5.4/')
                        and string(normalize-space(ancestor::docset/@setid))">
          <xsl:value-of select="concat($docset_from_url, $id.sep, ancestor::docset/@setid)"/>
        </xsl:when>
        <!-- Shared support-matrix links appear in multiple SUSE Edge docsets; include source setid. -->
        <xsl:when test="starts-with($href, '/suse-edge/support-matrix/html/support-matrix/')
                        and string(normalize-space(ancestor::docset/@setid))">
          <xsl:value-of select="concat($docset_from_url, $id.sep, ancestor::docset/@setid)"/>
        </xsl:when>
        <xsl:otherwise>
          <xsl:value-of select="$docset_from_url"/>
        </xsl:otherwise>
      </xsl:choose>
    </xsl:variable>

    <xsl:variable name="filename">
      <xsl:call-template name="substring-after-last">
        <xsl:with-param name="string" select="$href"/>
        <xsl:with-param name="char" select="'/'"/>
      </xsl:call-template>
    </xsl:variable>

    <xsl:variable name="doc_from_url">
      <xsl:choose>
        <xsl:when test="starts-with($href, '/')">
          <xsl:value-of select="substring-after($href, concat('/', $pid, '/', $docset_from_url, '/'))"/>
        </xsl:when>
        <xsl:when test="contains($href, 'external-tree')">
          <xsl:value-of select="substring-after($href, concat($pid, '/', $docset_from_url, '/'))"/>
        </xsl:when>
        <xsl:otherwise>
          <xsl:value-of select="$filename"/>
        </xsl:otherwise>
      </xsl:choose>
    </xsl:variable>

    <xsl:variable name="doc">
      <xsl:choose>
        <xsl:when test="not(string($doc_from_url))">
          <xsl:value-of select="concat(ancestor::product/@productid, '-', ancestor::docset/@setid)"/>
        </xsl:when>
        <xsl:when test="contains($doc_from_url, '.html')">
           <xsl:value-of select="translate(substring-before($doc_from_url, '.html'), '/', '-')"/>
        </xsl:when>
        <xsl:when test="contains($doc_from_url, '.pdf')">
           <xsl:value-of select="translate(substring-before($doc_from_url, '.pdf'), '/', '-')"/>
        </xsl:when>
        <xsl:when test="substring($doc_from_url, string-length($doc_from_url)) = '/'">
          <!-- URL ends with slash - preserve version/path info: "6.2/" → "6-2" -->
          <xsl:value-of select="translate(
                                   substring(
                                     $doc_from_url,
                                     1,
                                     string-length($doc_from_url) - 1
                                   ),
                                   './', '--'
                                 )"/>
        </xsl:when>
        <xsl:when test="contains($doc_from_url, '.')">
           <xsl:value-of select="translate(substring-before($doc_from_url, '.'), '/', '-')"/>
        </xsl:when>
        <xsl:otherwise>
           <xsl:value-of select="translate($doc_from_url, '/', '-')"/>
        </xsl:otherwise>
      </xsl:choose>
    </xsl:variable>

    <!-- Extract and normalize title for disambiguation when multiple links have same URL structure -->
    <xsl:variable name="title">
      <xsl:choose>
        <xsl:when test="language[@lang='en-us']">
          <xsl:value-of select="language[@lang='en-us'][1]/@title"/>
        </xsl:when>
        <xsl:otherwise>
          <xsl:value-of select="language[1]/@title"/>
        </xsl:otherwise>
      </xsl:choose>
    </xsl:variable>
    <xsl:variable name="normalized_title">
      <xsl:if test="string($title)">
        <xsl:value-of select="translate($title,
                                concat(&uppercase;, ', /:&amp;()'),
                                concat(&lowercase;, '-------')
                              )"/>
      </xsl:if>
    </xsl:variable>

    <xsl:variable name="doc_with_title">
      <xsl:value-of select="$doc"/>
      <xsl:if test="string($normalized_title) and not(contains($doc, translate($normalized_title, '-', '')))">
        <xsl:value-of select="concat($id.sep, $normalized_title)"/>
      </xsl:if>
    </xsl:variable>

    <xsl:variable name="id">
       <xsl:call-template name="generate.id">
         <xsl:with-param name="product.idabbrev" select="$product.idabbrev"/>
         <xsl:with-param name="docset" select="$docset_for_id"/>
         <xsl:with-param name="dc" select="$doc_with_title"/>
       </xsl:call-template>
    </xsl:variable>

    <deliverable id="{$id}" type="prebuilt">
      <xsl:apply-templates select="@category" mode="builddocs" />
      <xsl:apply-templates
        select="language[@lang='en-us'][1] | language[1][not(../language[@lang='en-us'])]"
        mode="builddocs" />
    </deliverable>
  </xsl:template>


  <xsl:template match="link/@category | deliverable/@category" mode="builddocs">
    <xsl:call-template name="write-category-attribute"/>
  </xsl:template>

  <xsl:template match="docset/external/link/language" mode="builddocs">
    <prebuilt>
      <title><xsl:value-of select="normalize-space(@title)"/></title>
      <xsl:apply-templates select="url"/>
      <descriptions>
          <desc lang="en-us">
            <p><xsl:comment>TODO</xsl:comment></p>
          </desc>
      </descriptions>
    </prebuilt>
  </xsl:template>


  <xsl:template match="url" mode="builddocs">
    <xsl:copy>
      <xsl:copy-of select="@*|../@lang" />
    </xsl:copy>
  </xsl:template>

  <!-- builddocs -->
  <xsl:template match="builddocs/language">
    <xsl:variable name="has.external.prebuilt" select="@lang = 'en-us' and ../../external/link[not(starts-with(language/url/@href, 'https://'))]" />
    <xsl:choose>
      <xsl:when test="deliverable or $has.external.prebuilt">
        <locale lang="{@lang}">
          <xsl:if test="$sitemap.for.translations = 'false'">
            <xsl:attribute name="sitemap">false</xsl:attribute>
          </xsl:if>
          <xsl:apply-templates />
          <xsl:if test="$has.external.prebuilt">
            <xsl:apply-templates select="../../external/link[not(starts-with(language/url/@href, 'https://'))]" mode="builddocs" />
          </xsl:if>
        </locale>
      </xsl:when>
      <xsl:otherwise>
        <xsl:comment>
          <xsl:text>&#10;        &lt;language lang=&quot;</xsl:text>
          <xsl:value-of select="@lang"/>
          <xsl:text>&quot;</xsl:text>
          <xsl:if test="@translation-type">
            <xsl:text> translation-type=&quot;</xsl:text>
            <xsl:value-of select="@translation-type"/>
            <xsl:text>&quot;</xsl:text>
          </xsl:if>
          <xsl:text>&gt;&#10;</xsl:text>
          <xsl:if test="branch">
            <xsl:text>          &lt;branch&gt;</xsl:text>
            <xsl:value-of select="branch"/>
            <xsl:text>&lt;/branch&gt;&#10;</xsl:text>
          </xsl:if>
          <xsl:if test="subdir">
            <xsl:text>          &lt;subdir&gt;</xsl:text>
            <xsl:value-of select="subdir"/>
            <xsl:text>&lt;/subdir&gt;&#10;</xsl:text>
          </xsl:if>
          <xsl:text>        &lt;/language&gt;&#10;      </xsl:text>
        </xsl:comment>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <xsl:template match="builddocs/language/@default" />

  <xsl:template match="builddocs/buildcontainer">
    <xsl:comment>
      &lt;buildcontainer image="<xsl:value-of select="@image"/>" />
    </xsl:comment>
  </xsl:template>


  <!-- regular <deliverable> -->
  <xsl:template match="language[@lang='en-us']/deliverable">
    <xsl:variable name="pid" select="ancestor::product/@productid"/>
    <xsl:variable name="abbrev" select="$config/product[@id=$pid]/@idabbrev"/>
    <xsl:variable name="product.idabbrev" select="$abbrev | $pid[not($abbrev)]"/>
    <xsl:variable name="id">
      <xsl:call-template name="generate.id">
        <xsl:with-param name="product.idabbrev" select="$product.idabbrev"/>
        <xsl:with-param name="docset" select="ancestor::docset/@setid"/>
        <xsl:with-param name="dc" select="dc"/>
      </xsl:call-template>
    </xsl:variable>

    <deliverable id="{$id}" type="dc">
      <xsl:apply-templates select="@*"/>
      <dc file="{normalize-space(dc/text())}">
        <xsl:apply-templates />
      </dc>
    </deliverable>
  </xsl:template>

  <xsl:template match="dc|dc/text()" />

  <xsl:template match="language[@lang='en-us']/deliverable/@category">
    <xsl:call-template name="write-category-attribute"/>
  </xsl:template>


  <!-- translated <deliverable> -->
  <xsl:template match="language[@lang!='en-us']/deliverable">
    <xsl:variable name="pid" select="ancestor::product/@productid"/>
    <xsl:variable name="abbrev" select="$config/product[@id=$pid]/@idabbrev"/>
    <xsl:variable name="product.idabbrev" select="$abbrev | $pid[not($abbrev)]"/>
    <xsl:variable name="id">
      <xsl:call-template name="generate.id">
        <xsl:with-param name="product.idabbrev" select="$product.idabbrev"/>
        <xsl:with-param name="docset" select="ancestor::docset/@setid"/>
        <xsl:with-param name="dc" select="dc"/>
      </xsl:call-template>
    </xsl:variable>

    <deliverable type="ref">
      <ref linkend="{$id}" />
    </deliverable>
  </xsl:template>

  <xsl:template match="language[@lang!='en-us']/deliverable/@category">
    <xsl:call-template name="write-category-attribute"/>
  </xsl:template>

  <xsl:template match="subdeliverable/@category">
    <xsl:call-template name="write-category-attribute"/>
  </xsl:template>

  <!-- ref  -->
  <xsl:template match="ref">
    <xsl:variable name="pid" select="@product"/>
    <xsl:variable name="cnfg" select="$config/product[@id=$pid]"/>
    <xsl:variable name="abbrev" select="$cnfg/@idabbrev"/>
    <xsl:variable name="product.idabbrev" select="$abbrev | $pid[not($abbrev)]"/>
    <xsl:variable name="ref" >
      <xsl:choose>
        <xsl:when test="not(@docset) and not(@dc)">
          <xsl:call-template name="generate.id">
            <xsl:with-param name="product.idabbrev" select="$product.idabbrev"/>
          </xsl:call-template>
        </xsl:when>
        <xsl:when test="@product and @docset and not(@dc)">
          <xsl:call-template name="generate.id">
            <xsl:with-param name="product.idabbrev" select="$product.idabbrev"/>
            <xsl:with-param name="docset" select="@docset"/>
          </xsl:call-template>
        </xsl:when>
        <xsl:when test="@product and @docset and @dc">
          <xsl:call-template name="generate.id">
            <xsl:with-param name="product.idabbrev" select="$product.idabbrev"/>
            <xsl:with-param name="docset" select="@docset"/>
            <xsl:with-param name="dc" select="@dc"/>
          </xsl:call-template>
        </xsl:when>
        <xsl:when test="@deliverable">
          <xsl:value-of select="concat(@product, $id.sep, @docset, $id.sep, @deliverable)"/>
        </xsl:when>
        <xsl:otherwise>
          <xsl:message>WARN: Couldn't create a linkend for &lt;ref <xsl:for-each select="@*">
              <xsl:value-of select="concat(local-name(.), '=&quot;', ., '&quot; ')"/>
          </xsl:for-each>
          <xsl:text>/&gt;</xsl:text>
          </xsl:message>
        </xsl:otherwise>
      </xsl:choose>
    </xsl:variable>
    <!--<xsl:message>ref: <xsl:value-of select="count($cnfg)"/>
      product=<xsl:value-of select="concat(@product, '::', $pid)"/>
      idabbrev=<xsl:value-of select="$abbrev"/>
    </xsl:message>-->
    <ref linkend="{$ref}">
      <xsl:apply-templates select="@category|@titleformat"/>
    </ref>
  </xsl:template>

  <xsl:template match="ref/@category">
    <xsl:variable name="owner.productid" select="ancestor::product[1]/@productid"/>
    <xsl:call-template name="write-category-attribute">
      <xsl:with-param name="productid" select="$owner.productid"/>
      <xsl:with-param name="has-product-categories" select="/docservconfig/product[@productid = $owner.productid]/category"/>
    </xsl:call-template>
  </xsl:template>

  <!-- desc -->
  <xsl:template match="desc/@default" />

</xsl:stylesheet>
