name: Documentation Update
description: Propose improvements or corrections to the documentation.
labels: ["area:documentation"]
type: task


body:
  - type: markdown
    attributes:
      value: |
        Help us improve the documentation! Please describe what needs updating.

  - type: dropdown
    id: affected_section
    attributes:
      label: Affected Documentation Section(s)
      description: Select the section(s) of the documentation that need updating.
      multiple: true
      options:
        - "User"
        - "Developer"
        - "Reference"
        - "API"
        - "Glossary"
        - "Other (describe below)"
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Change
      description: What should be changed or improved?
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Context
      description: Any other information, screenshots, or references?
    validations:
      required: false
