name: Build and Deploy Sphinx Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'test-docs?-**'
    tags:
      - '[0-9]*.[0-9]*.[0-9]*'
    paths:
      - 'docs/**'
      - '.github/workflows/gh-pages.yml'
      - 'src/docbuild/__about__.py'

permissions:
  contents: write

env:
  CI_BIN_DIR: .github/bin

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install Graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz

      - name: Install the latest version of uv
        id: setup-uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
          enable-cache: true
          cache-suffix: "docbuild"

      - name: Print uv debug information
        run: |
          echo "Installed uv version is ${{ steps.setup-uv.outputs.uv-version }}"
          echo "Installed uv path is ${{ steps.setup-uv.outputs.uv-path }}"
          echo "Set Python version is ${{ steps.setup-uv.outputs.python-version }}"

      - name: Install dependencies
        run: uv sync --frozen --group docs

      - name: Determine documentation version
        run: ${{ env.CI_BIN_DIR }}/determine-version.sh

      - name: Build documentation
        env:
          DOC_VERSION: ${{ env.DOC_VERSION }}
          TARGET_DIR: ${{ env.TARGET_DIR }}
        run: |
          # The DOC_VERSION is handled inside conf.py using os.environ
          uv run make -C docs html

      - name: Prepare deployment
        env:
          TARGET_DIR: ${{ env.TARGET_DIR }}
        run: ${{ env.CI_BIN_DIR }}/prepare-deploy.sh

      - name: Generate versions.json
        run: ${{ env.CI_BIN_DIR }}/generate-versions.py --output versions.json

      - name: Debug GITHUB_ENV
        run: echo $GITHUB_ENV

      - name: Debug ${{ env.TARGET_DIR }}
        run: ls -R "deploy/${{ env.TARGET_DIR }}" || exit 10

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy

      - name: Print documentation URL
        run: |
            echo "Documentation URL: "
            echo "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
